import { Product } from '../types';

// Edita este arreglo para cambiar precios, nombres, descripciones o fotos de los productos.
// Las imágenes esperadas están en public/images; reemplaza esos archivos por las fotos reales.
export const products: Product[] = [
  {
    id: 'choc-100',
    categoria: 'chocolate',
    nombre: 'Chocolate 100 g',
    descripcion: 'Tableta artesanal de chocolate, perfecta para un detalle dulce.',
    tipoMedida: 'gramos',
    cantidad: 100,
    precio: 5000,
    imageUrl: '/images/chocolate-100g.jpg',
  },
  {
    id: 'choc-250',
    categoria: 'chocolate',
    nombre: 'Chocolate 250 g',
    descripcion: 'Chocolate de receta casera, ideal para compartir.',
    tipoMedida: 'gramos',
    cantidad: 250,
    precio: 10000,
    imageUrl: '/images/chocolate-250g.jpg',
  },
  {
    id: 'choc-500',
    categoria: 'chocolate',
    nombre: 'Chocolate 500 g',
    descripcion: 'Una barra generosa con ingredientes seleccionados.',
    tipoMedida: 'gramos',
    cantidad: 500,
    precio: 15000,
    imageUrl: '/images/chocolate-500g.jpg',
  },
  {
    id: 'choc-1000',
    categoria: 'chocolate',
    nombre: 'Chocolate 1.000 g',
    descripcion: 'Un kilo de chocolate artesanal para celebraciones especiales.',
    tipoMedida: 'gramos',
    cantidad: 1000,
    precio: 20000,
    imageUrl: '/images/chocolate-1000g.jpg',
  },
  {
    id: 'alf-6',
    categoria: 'alfajor',
    nombre: 'Caja de 6 alfajores',
    descripcion: 'Clásicos alfajores bañados en chocolate con relleno casero.',
    tipoMedida: 'unidades',
    cantidad: 6,
    precio: 5000,
    imageUrl: '/images/alfajores-6.jpg',
  },
  {
    id: 'alf-12',
    categoria: 'alfajor',
    nombre: 'Caja de 12 alfajores',
    descripcion: 'Surtido perfecto para compartir en familia o con amigos.',
    tipoMedida: 'unidades',
    cantidad: 12,
    precio: 10000,
    imageUrl: '/images/alfajores-12.jpg',
  },
  {
    id: 'alf-18',
    categoria: 'alfajor',
    nombre: 'Caja de 18 alfajores',
    descripcion: 'Selección amplia con relleno suave y cobertura de chocolate.',
    tipoMedida: 'unidades',
    cantidad: 18,
    precio: 15000,
    imageUrl: '/images/alfajores-18.jpg',
  },
  {
    id: 'alf-24',
    categoria: 'alfajor',
    nombre: 'Caja de 24 alfajores',
    descripcion: 'Ideal para eventos, celebraciones o regalos especiales.',
    tipoMedida: 'unidades',
    cantidad: 24,
    precio: 20000,
    imageUrl: '/images/alfajores-24.jpg',
  },
];
